language: node_js
node_js:
  - "0.10"
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c271f1bb1172ede44e00
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
